config/routes.rb
Rails.application.routes.draw do
  resources :items
  post '/items/:id/sign_up', to: 'items#sign_up', as: 'sign_up'
  post '/items/:id/password', to: 'items#input_password', as: 'item_input_password'
  get '/emails/:id/:validation_token', to: 'emails#validate', as: 'validate'
  root to: 'items#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
	belongs_to :item

	def send_success_msg
		UserMailer.success_email(self).deliver_later unless self.sent_success_msg 
		self.update(sent_success_msg: true)
	end
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :emails
	validates :threshold, numericality: {greater_than: 0}

	def validated_signups
		self.emails.where(validated: true)
	end

	def succeeded?
		if self.validated_signups.count >= self.threshold
			self.validated_signups.where(sent_success_msg: false).each do |email|
				email.send_success_msg 
			end
			return true
		end
		return false
	end

	def self.hash(password)
		Digest::SHA256.base64digest(password || '')
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
	def validate
		email = Email.find(params[:id])
		if email.validation_token == params[:validation_token]
			email.validated = true
			email.save!
		end

		item = email.item 
		item.succeeded?
		redirect_to item_url(item), notice: "Verified"
	end
end

app/controllers/items_controller.rb
require 'digest'
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :check_edit_authorization, only: [:edit, :update]

  # GET /items
  # GET /items.json
  def index
    @items = Item.where(public: true).order('created_at DESC')
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  def sign_up
    @email = Email.new({email: params[:email], 
                        validated: false,
                        validation_token: SecureRandom.hex,
                        item_id: params[:id]
                        })
    respond_to do |format|
      if @email.save
        UserMailer.validation_email(@email).deliver_later
        format.html { redirect_to item_url(params[:id]), notice: "Signed up - validate your email"}
      else
        format.html { redirect_to item_url(params[:id]), notice: 'Error' }
      end
    end
  end

  def input_password
    password_hash = Item.hash(params[:password])
    @item = Item.find(params[:id])
    if Item.hash(params[:password]) == @item.password_hash
      session[:current_edit] = @item.id
      redirect_to edit_item_url(params[:id])
    else
      redirect_to item_url(params[:id]), notice: 'Wrong password'
    end
  end

  # POST /items
  # POST /items.json
  def create
    item_params = item_create_params
    item_params[:password_hash] = Item.hash(params[:item][:password])
    p item_params
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_update_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def item_update_params
      params.require(:item).permit(:success_msg, :public, :show_threshold, :show_verified_signups)
    end

    def item_create_params
      params.require(:item).permit(:title, :description, :threshold, :success_msg, :public, :show_threshold, :show_verified_signups)
    end

    def check_edit_authorization
      if !session[:current_edit] || session[:current_edit] != params[:id].to_i
        redirect_to item_url(params[:id]), notice: "You aren't authorized to edit this item"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_edit_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="not-field">
    Title: <%= @item.title %>
  </div>

  <div class="not-field">
    Description: <%= @item.description %>
  </div>

  <div class="not-field">
    Threshold: <%= @item.threshold %>
  </div>

  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :public, id: :item_public %>
  </div>

  <div class="field">
    <%= form.label :show_threshold %>
    <%= form.check_box :show_threshold, id: :item_show_threshold %>
  </div>

  <div class="field">
    <%= form.label :show_verified_signups %>
    <%= form.check_box :show_verified_signups, id: :item_show_verified_signups %>
  </div>

  <div class="field">
    <%= form.label :success_msg %>
    <%= form.text_area :success_msg, id: :item_success_msg %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :item_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :item_description %>
  </div>

  <div class="field">
    <%= form.label :threshold %>
    <%= form.number_field :threshold, id: :item_threshold, min: 1 %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :item_password %>
  </div>

  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :public, id: :item_public %>
  </div>

  <div class="field">
    <%= form.label :show_threshold %>
    <%= form.check_box :show_threshold, id: :item_show_threshold %>
  </div>

  <div class="field">
    <%= form.label :show_verified_signups %>
    <%= form.check_box :show_verified_signups, id: :item_show_verified_signups %>
  </div>

  <div class="field">
    <%= form.label :success_msg %>
    <%= form.text_area :success_msg, id: :item_success_msg %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Stats</h1>
This item has <%= @item.validated_signups.count %> validated signups.

<h1>Edit</h1>

<%= render 'edit_form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.title, item %></td>
        <td><%= item.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
	<% if @item.show_threshold %>
		<strong>Threshold:</strong> <%= @item.threshold %>
	<% end %>
	<% if @item.show_verified_signups %>
		<strong>Verified signups:</strong> <%= @item.validated_signups.count %>
	<% end %> 
</p>

<%= form_tag({controller: 'items', action: 'sign_up', id: @item.id}, method: 'post') do %>
<p><strong>Add your email:</strong>

	<%= text_field_tag :email %>
	<%= submit_tag "Sign up" %>
<% end %>

<%= link_to 'Back', items_path %>

<%= form_tag({controller: 'items', action: 'input_password', id: @item.id}, method: 'post') do %>
	Enter password to edit: 
	<%= text_field_tag :password %>
	<%= submit_tag "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Actuator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>